### ISSUE TITLE
TypeError: TopDownBDD100KPoseDataset: TopDownCocoDataset.__init__() got an unexpected keyword argument 'dataset_info'

### ISSUE THREAD

**Issue by afnan29alofi** [SysCV/bdd100k-models#24]
hi, 
when i try run the pose test I get this error  
code : 
!python test.py /content/bdd100k-models/pose/configs/pose/hrnet_w32_256x192_1x_pose_bdd100k.py --gpu_collect --format-dir /content/

error : 

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/mmcv/utils/registry.py", line 51, in build_from_cfg
    return obj_cls(**args)
TypeError: TopDownCocoDataset.__init__() got an unexpected keyword argument 'dataset_info'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/content/bdd100k-models/pose/test.py", line 132, in <module>
    main()
  File "/content/bdd100k-models/pose/test.py", line 89, in main
    dataset = build_dataset(cfg.data.test, dict(test_mode=True))
  File "/usr/local/lib/python3.10/dist-packages/mmpose/datasets/builder.py", line 44, in build_dataset
    dataset = build_from_cfg(cfg, DATASETS, default_args)
  File "/usr/local/lib/python3.10/dist-packages/mmcv/utils/registry.py", line 54, in build_from_cfg
    raise type(e)(f'{obj_cls.__name__}: {e}')
TypeError: TopDownBDD100KPoseDataset: TopDownCocoDataset.__init__() got an unexpected keyword argument 'dataset_info'

**Comment by thomasehuang** [comment]
This may be due to the version of `mmpose`. Can you try installing `mmpose==0.18.0` and running the code again?

**Comment by Marchetz** [comment]
Hi, I have the same problem and I have installed mmpose version 0.18.0. Maybe the problem is something else...
