### ISSUE TITLE
ImportError: cannot import name 'DATASETS' from 'mmdet.datasets'

### ISSUE THREAD

**Issue by marcsava** [SysCV/bdd100k-models#25]
In order to make inference with the bdd100k detection models, I launched the test.py script as indicated in the guide (after having installed everything necessary):

python ./test.py "/user/msavarese/bdd100k-models/det/configs/det/atss_r101_fpn_3x_det_bdd100k.py" --format-only --format-dir "/user/msavarese/det.json" [--cfg -options]

I get the following error:

Traceback (most recent call last):
   File "./test.py", line 6, in <module>
     import datasets # pylint: disable=unused-import
   File "/user/msavarese/bdd100k-models/det/datasets/__init__.py", line 3, in <module>
     from .bdd100k import BDD100KDetDataset
   File "/user/msavarese/bdd100k-models/det/datasets/bdd100k.py", line 8, in <module>
     from mmdet.datasets import DATASETS, CocoDataset
ImportError: cannot import name 'DATASETS' from 'mmdet.datasets' (/user/msavarese/miniconda3/envs/bdd100k-mmdet/lib/python3.8/site-packages/mmdet/datasets/__init__.py)

**Comment by thomasehuang** [comment]
This is probably due to your version of MMDetection. We are currently using `mmdet<3.0`. If your version is 3.0 or above you may need to downgrade it by doing `pip install 'mmdet<3.0'`.

**Comment by shanhx2000** [comment]
Hi Thomas, I'm trying to use this repo. However, during installation, I noticed mmdet<3.0 requires mmcv<=1.8.0, which is not compatible with most mmcv-based applications.
